-- 1. GRANT access to orders table
GRANT SELECT, INSERT, UPDATE ON orders TO authenticated;

-- 2. Create notifications table if missing
CREATE TABLE IF NOT EXISTS notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  title text not null,
  message text,
  type text default 'info',
  read boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Grant + RLS for notifications
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON notifications TO authenticated;
CREATE POLICY "Users can view own notifications"
ON notifications FOR SELECT TO authenticated
USING (auth.uid() = user_id);
CREATE POLICY "Users can update own notifications"
ON notifications FOR UPDATE TO authenticated
USING (auth.uid() = user_id);

-- 3. Orders RLS
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own orders"
ON orders FOR SELECT TO authenticated
USING (auth.uid() = user_id);

-- 4. Upgrade super admin
INSERT INTO profiles (id, email, role, full_name)
SELECT id, email, 'super_admin', 'Mambwe Mwila'
FROM auth.users WHERE email = 'mambwemwila1@gmail.com'
ON CONFLICT (id) DO UPDATE SET role = 'super_admin';

-- 5. Reload PostgREST cache
NOTIFY pgrst, 'reload schema';
NOTIFY pgrst, 'reload config';
