-- ==========================================
-- Phase 3: System Settings & Dynamic Commissions
-- ==========================================

BEGIN;

-- 1. Create System Settings Table
CREATE TABLE IF NOT EXISTS public.platform_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key text NOT NULL UNIQUE,
    setting_value text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- 2. Insert Default Commission Setting (10%)
INSERT INTO public.platform_settings (setting_key, setting_value, description)
VALUES ('platform_commission_percent', '10', 'Global percentage fee taken by the platform on each order')
ON CONFLICT (setting_key) DO NOTHING;

-- 3. Create RPC Function to safely fetch the commission rate
CREATE OR REPLACE FUNCTION public.get_platform_commission_rate()
RETURNS numeric
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_rate numeric;
BEGIN
    SELECT NULLIF(setting_value, '')::numeric INTO v_rate 
    FROM public.platform_settings 
    WHERE setting_key = 'platform_commission_percent';
    
    RETURN COALESCE(v_rate, 10.0); -- Safely fall back to 10% if missing
EXCEPTION
    WHEN OTHERS THEN
        RETURN 10.0; -- Fall back to 10% if parsing fails
END;
$$;

-- 4. RLS Policies
ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;

-- Everyone can read settings (needed for frontend UI if required)
DROP POLICY IF EXISTS "Public read system settings" ON public.platform_settings;
CREATE POLICY "Public read system settings" ON public.platform_settings FOR SELECT USING (true);

-- Only Super Admins can update system settings
DROP POLICY IF EXISTS "Super Admins manage system settings" ON public.platform_settings;
CREATE POLICY "Super Admins manage system settings" ON public.platform_settings 
FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() 
        AND role = 'super_admin'
    )
);

-- Service role bypasses RLS
GRANT ALL ON TABLE public.platform_settings TO service_role;

COMMIT;
