// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nngzclreycvdgycyuqoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZ3pjbHJleWN2ZGd5Y3l1cW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjg5NzEsImV4cCI6MjA3MzYwNDk3MX0.dZZPpbDXI33Lr64JCbM-CfTx9hZRCRKSTQ0MFlFoYdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});