// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khixmntoijxjrqmecwqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoaXhtbnRvaWp4anJxbWVjd3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzI2MTYsImV4cCI6MjA2Njk0ODYxNn0.ki-oQeb_RrGX_KaHtQaxOm-ExQSiK-Or_nr7sKRKIig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});